Cleanup and Py3 Support
heroku/python-telex pull request #3
Opened 2017-08-14 16:18 UTC by iamjem

This just does some general cleanup, and adds explicit testing with tox for various python 3 versions.

2017-08-14 19:06 UTC, sigmavirus24 requested changes
The substance of this change is fine with the exception of the license change in `setup.py`. I have some suggestions and concerns around the rest of this.

2017-08-14 19:06 UTC, sigmavirus24 commented on setup.py
> -with open('telex/__init__.py', 'r') as fd:
I'm confused, what does removing this have to do with Python 3?

2017-08-14 19:06 UTC, sigmavirus24 commented on setup.py
> +        'Programming Language :: Python :: 3.3',
I'd rather we just support 3.6. 3.3 support is being dropped by Requests so at least make the lower limit 3.4 if we want to support such a large swath.

2017-08-14 19:06 UTC, sigmavirus24 commented on telex/__init__.py
>  __version__ = '0.0.1'
If we're statically declaring the version in `setup.py` why not remove this?

2017-08-14 19:06 UTC, sigmavirus24 commented on tests/requirements.txt
> -httmock==1.2.3
Why not keep this and alter the `tox.ini` to be smarter?

2017-08-14 19:06 UTC, sigmavirus24 commented on tox.ini
> +deps=pytest
We could do `-rtests/requirements.txt` instead.

2017-08-14 19:06 UTC, sigmavirus24 commented on .gitignore
> -.venv/
I don't think it hurts to keep these two around. I get the sense that the team doesn't necessary embrace `tox` so having virtualenv directories be ignored seems like a harmless idea.

2017-08-14 19:06 UTC, sigmavirus24 commented on setup.py
> +    version='0.0.1',
Also, a revision like this probably warrants a new version number.

2017-08-14 19:06 UTC, sigmavirus24 commented on setup.py
> +with open('LICENSE') as f:
We don't want to read the text of the license into memory and shove it into our package metadata. That will break rendering of the README if we upload to PyPI.

2017-08-14 19:06 UTC, sigmavirus24 commented on setup.py
> +    license=license,
As I mentioned above, this should stay as `MIT`. Otherwise, PyPI will be fail to render the information about the package.

2017-08-14 19:24 UTC, sigmavirus24 commented
We should probably turn on Travis or Circle for this repository too

2017-08-14 19:28 UTC, iamjem commented on setup.py
> -with open('telex/__init__.py', 'r') as fd:
Nothing, it just seemed unnecessary. Could also import `__version__` explicitly I guess too.

2017-08-14 19:29 UTC, iamjem commented on setup.py
> +    license=license,
Hrmm we do this in some of our other packages too. I guess we should fix that as we're going through them for this if applicable.

2017-08-14 19:30 UTC, iamjem commented on tox.ini
> +deps=pytest
Right I did this on another package I'm fixing right now. Wasn't aware it was an option till I was looking through the docs more. I can update here I guess, ultimately there's so few test requirements I don't think it matters one way or another.

2017-08-14 19:37 UTC, iamjem commented on .gitignore
> -.venv/
The team has largely switched to using virtualenvwrapper and we typically keep the envs outside of the project (we use to all keep them in `.venv`). But, still valid point, might as well leave it.

2017-08-14 21:56 UTC, iamjem commented
Thanks for the great feedback. I believe I answered all of your comments, let me know if there's anything else I should consider changing.

2017-08-15 12:42 UTC, sigmavirus24 approved these changes
Looks good! :shipit:

2017-08-15 15:40 UTC, merged